export const testIds = {
  debugShell: 'debug-shell',
  chatPageRoot: 'chat-page-root',
  modalOverlay: 'modal-overlay',
  modalContent: 'modal-content',
  tabsPrefix: 'tabs-',
  statusIndicator: 'status-indicator',
  loadingSpinner: 'loading-spinner',
  messageList: 'message-list',
  messageBubble: 'message-bubble',
  composerInput: 'composer-input',
  sendButton: 'send-button',
  sessionSelector: 'session-selector',
  thinkingBlock: 'thinking-block',
  selectedElementCard: 'selected-element-card',
  domElementsTable: 'dom-elements-table',
  actionButton: 'action-button',
  domTableRow: 'dom-table-row',
  configPanel: 'config-panel',
  healthStatusCard: 'health-status-card',
  mcpStatusList: 'mcp-status-list',
  mcpServerItem: 'mcp-server-item',
  mcpServerViewBtn: 'mcp-server-view-btn',
  mcpToolsModal: 'mcp-tools-modal',
  interactionsTable: 'interactions-table',
  interactionDetailModal: 'interaction-detail-modal',
  interactionsTableRow: 'interactions-table-row',
  interactionFilterActionType: 'interaction-filter-action-type',
  interactionFilterSuccess: 'interaction-filter-success',
  // Layout
  activityBar: 'activity-bar',
  activityBtnMonitor: 'activity-btn-monitor',
  activityBtnControl: 'activity-btn-control',
  activityBtnAi: 'activity-btn-ai',
  activityBtnChat: 'activity-btn-chat',

  debugSidebar: 'debug-sidebar',
  debugMain: 'debug-main',
  debugRightPanel: 'debug-right-panel',
  rightPanelTabDomElements: 'right-panel-tab-dom-elements',
  rightPanelTabConfig: 'right-panel-tab-config',
  // Status
  playwrightStatus: 'playwright-status',
  // Control Browser Basic
  controlBrowserBasicStatus: 'control-browser-basic-status',
  controlBrowserBasicStatusIndicator: 'control-browser-basic-status-indicator',
  controlBrowserBasicStatusText: 'control-browser-basic-status-text',
  controlBrowserBasicCurrentUrl: 'control-browser-basic-current-url',
  controlBrowserBasicOpenBtn: 'control-browser-basic-open-btn',
  controlBrowserBasicCloseBtn: 'control-browser-basic-close-btn',
  controlBrowserBasicUrlInput: 'control-browser-basic-url-input',
  controlBrowserBasicNavigateBtn: 'control-browser-basic-navigate-btn',
  controlBrowserBasicScreenshotBtn: 'control-browser-basic-screenshot-btn',
  controlBrowserBasicReconnectBtn: 'control-browser-basic-reconnect-btn',
  // LiveView
  liveviewCanvas: 'liveview-canvas',
  liveviewDomHighlight: 'liveview-dom-highlight',
  liveviewPickerCursor: 'liveview-picker-cursor',
  // Control Operation Logs
  controlOperationLogs: 'control-operation-logs',
  controlOperationLogsContainer: 'control-operation-logs-container',
  controlOperationLogsClearBtn: 'control-operation-logs-clear-btn',
  // Control - Page Interaction
  controlPageInteraction: 'control-page-interaction',
  controlPageInteractionElementPicker: 'control-page-interaction-element-picker',
  controlPageInteractionCoordX: 'control-page-interaction-coord-x',
  controlPageInteractionCoordY: 'control-page-interaction-coord-y',
  controlPageInteractionCoordClick: 'control-page-interaction-coord-click',
  controlPageInteractionSelectorMode: 'control-page-interaction-selector-mode',
  controlPageInteractionMarkerId: 'control-page-interaction-marker-id',
  controlPageInteractionCssSelector: 'control-page-interaction-css-selector',
  controlPageInteractionActionType: 'control-page-interaction-action-type',
  controlPageInteractionActionParam: 'control-page-interaction-action-param',
  controlPageInteractionExecute: 'control-page-interaction-execute',
  controlPageInteractionScrollX: 'control-page-interaction-scroll-x',
  controlPageInteractionScrollY: 'control-page-interaction-scroll-y',
  controlPageInteractionScroll: 'control-page-interaction-scroll',
  // Monitor Sidebar
  monitorSidebar: 'monitor-sidebar',
  monitorSidebarBrowserCard: 'monitor-sidebar-browser-card',
  monitorSidebarBrowserIndicator: 'monitor-sidebar-browser-indicator',
  monitorSidebarBrowserStatusText: 'monitor-sidebar-browser-status-text',
  monitorSidebarBrowserScreenshotBtn: 'monitor-sidebar-browser-screenshot-btn',
  monitorSidebarScreenshotCard: 'monitor-sidebar-screenshot-card',
  monitorSidebarSnapshotLabel: 'monitor-sidebar-snapshot-label',
  monitorSidebarSnapshotError: 'monitor-sidebar-snapshot-error',
  monitorSidebarSnapshotImg: 'monitor-sidebar-snapshot-img',
  monitorSidebarSnapshotRefreshBtn: 'monitor-sidebar-snapshot-refresh-btn',
  // Monitor Main
  monitorMain: 'monitor-main',
  monitorMainHeader: 'monitor-main-header',
  monitorMainStatusBadge: 'monitor-main-status-badge',
  monitorMainLiveview: 'monitor-main-liveview',
  monitorMainDownloadBtn: 'monitor-main-download-btn',
  monitorMainRefreshBtn: 'monitor-main-refresh-btn',
  // Config — new components
  configConnectivityTest: 'config-connectivity-test',
  configAiTest: 'config-ai-test',
  configContent: 'config-content',
  // DOM Elements
  domElementsMarkerToggle: 'dom-elements-marker-toggle',
  domElementsGetDomBtn: 'dom-elements-get-dom-btn',
  domElementsContainer: 'dom-elements-container',
  domElementsEmptyState: 'dom-elements-empty-state',
} as const;

export type TestId = (typeof testIds)[keyof typeof testIds];
